version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./todo-data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/todos.db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend